name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Source Files
        run: |
          # Using rSync
          rsync -Rr ./ ./paldmin/
  
      - name: Remove Unwanted Directories
        run: |
          rm -rf ./paldmin/docs && rm -rf ./paldmin/.git && rm -rf ./paldmin/.github
  
      - name: Create Artifact
        run: |
          tar -zcvf "paldmin-${{ github.event.inputs.release_version }}.tar.gz" ./paldmin

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: paldmin-${{ github.event.inputs.release_version }}.tar.gz
