name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Package Source Code
        run: |
          mkdir paldmin
          cp -r !(paldmin) paldmin
          tar -czvf "release-${{ github.event.inputs.release_version }}.tar.gz" -C paldmin .

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: release-${{ github.event.inputs.release_version }}.tar.gz
